apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-azl-vote-api
spec:
  provider: azure
  secretObjects:
  - secretName: azl-vote-api-secrets
    data:
    - key: DB-CONNECTION
      objectName: DB-CONNECTION
    type: Opaque
  parameters:
    usePodIdentity: "true"                                      
    useVMManagedIdentity: "false"                               
    userAssignedIdentityID: ""                                                                                                
    keyvaultName: "azl-vote-api-secrets"                                                                
    cloudName: ""                                               
    objects:  |
      array:
        - |
          objectName: DB-CONNECTION                              
          objectType: secret                                    
          objectVersion: ""                                     
    resourceGroup: "aks"                      
    subscriptionId: "3d186584-9824-4639-abef-016aee3c06cd"      
    tenantId: "14cbd5a7-ec94-46ba-b314-cc0fc972a161"